#!/bin/bash

if [[ "$OS_NAME" == Darwin ]]; then
  echo_info "Installing GNU binaries for OSX that aren't already installed"

  if ! which gls > /dev/null; then
    install_bin "coreutils"
  fi
  
  if [ $BASH_VERSINFO -lt 4 ]; then
    install_bin "bash"
  fi
fi

# Set the shell theme
if [ -z $BASE16_THEME ]; then
  THEME=snazzy
  BASE16_SHELL="$HOME/.config/base16-shell/"
  [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
    eval "$("$BASE16_SHELL/profile_helper.sh")"

  echo_info "Setting shell theme to: $BASE16_THEME"
  _base16 "/home/lobabob/.config/base16-shell/scripts/base16-$THEME.sh" $THEME
fi

