#!/bin/bash

if [[ "$OS_NAME" == Darwin ]]; then
  echo_info "Installing GNU binaries for OSX that aren't already installed"

  if ! which gls > /dev/null; then
    install_bin "coreutils"
  fi
  
  if [ $BASH_VERSINFO -lt 4 ]; then
    install_bin "bash"
  fi
fi

# Makes it convenient to cd to the dotfiles dir
already_exists=$(cat ~/.bash_aliases.extra 2> /dev/null | grep dotfiles)
if [[ -z "$already_exists" ]]; then
  echo "alias dotfiles=\"cd $(realpath $BASE_DIR)\"" >> $HOME/.bash_aliases.extra
fi

